export const FETCH_SALES = 'FETCH_SALES';
export const FETCH_SALES_START = 'FETCH_SALES_START';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_FAIL = 'FETCH_SALES_FAIL';

export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';